FROM golang:1.23-alpine AS builder

RUN apk update && apk upgrade && apk add --no-cache bash git openssh

WORKDIR /github.com/paw1a/sigma-school/
COPY . /github.com/paw1a/sigma-school/

RUN go mod download

RUN GOOS=linux GOARCH=arm64 go build -o ./.bin/app ./cmd/web/main.go


FROM alpine

WORKDIR /app

COPY --from=builder /github.com/paw1a/sigma-school/.bin/ .
COPY --from=builder /github.com/paw1a/sigma-school/config/ ./config/
COPY --from=builder /github.com/paw1a/sigma-school/docs/ ./docs/

EXPOSE 8080

CMD ["./app"]